"""Initial migration

Revision ID: 16830df1eba1
Revises: 
Create Date: 2026-01-11 22:54:16.262582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16830df1eba1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('spec', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_number')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.CheckConstraint("unit IN ('pcs', 'lmbr')", name='positions_unit_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('problem_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('sub_position_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sub_position_id'], ['sub_positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HADIR', 'IJIN', 'CUTI', 'ALPA', name='attendancestatus'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_coordinator', sa.Boolean(), nullable=True),
    sa.Column('approved_supervisor', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('sub_position_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty_output', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qty_reject', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('problem_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status_completion', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_coordinator', sa.Boolean(), nullable=True),
    sa.Column('approved_spv', sa.Boolean(), nullable=True),
    sa.Column('approved_coordinator_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('approved_spv_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('approved_coordinator_by', sa.Integer(), nullable=True),
    sa.Column('approved_spv_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(approved_spv IS NULL) OR (approved_coordinator = true)', name='spv_after_coordinator_check'),
    sa.CheckConstraint('problem_duration_minutes >= 0', name='production_logs_problem_duration_minutes_check'),
    sa.CheckConstraint('qty_output >= 0', name='production_logs_qty_output_check'),
    sa.CheckConstraint('qty_reject >= 0', name='production_logs_qty_reject_check'),
    sa.ForeignKeyConstraint(['approved_coordinator_by'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['approved_spv_by'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['sub_position_id'], ['sub_positions.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('sub_position_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['workers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_position_id'], ['sub_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_log_problem_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_log_id', sa.BigInteger(), nullable=False),
    sa.Column('problem_comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_comment_id'], ['problem_comments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_log_id'], ['production_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_log_problem_comments')
    op.drop_table('production_plan')
    op.drop_table('production_logs')
    op.drop_table('attendances')
    op.drop_table('workers')
    op.drop_table('production_targets')
    op.drop_table('sub_positions')
    op.drop_table('departments')
    op.drop_table('suppliers')
    op.drop_table('shifts')
    op.drop_table('problem_comments')
    op.drop_table('positions')
    op.drop_table('items')
    op.drop_table('divisions')
    # ### end Alembic commands ###

