"""add_approval_columns_to_attendance

Revision ID: 2a2866fcadda
Revises: 5444f4c004a8
Create Date: 2026-01-02 13:22:30.421522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2866fcadda'
down_revision: Union[str, None] = '5444f4c004a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('approved_coordinator', sa.Boolean(), nullable=True))
    op.add_column('attendances', sa.Column('approved_supervisor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'approved_supervisor')
    op.drop_column('attendances', 'approved_coordinator')
    # ### end Alembic commands ###

