"""add_position_id_and_sub_position_id_to_production_targets

Revision ID: 65cfdb462456
Revises: 8ead7175c3d0
Create Date: 2026-01-02 11:13:28.575844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cfdb462456'
down_revision: Union[str, None] = '8ead7175c3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_targets', sa.Column('position_id', sa.Integer(), nullable=True))
    op.add_column('production_targets', sa.Column('sub_position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'production_targets', 'sub_positions', ['sub_position_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'production_targets', 'positions', ['position_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_targets', type_='foreignkey')
    op.drop_constraint(None, 'production_targets', type_='foreignkey')
    op.drop_column('production_targets', 'sub_position_id')
    op.drop_column('production_targets', 'position_id')
    # ### end Alembic commands ###

