"""create_production_targets_and_add_target_id_to_positions

Revision ID: 8ead7175c3d0
Revises: 002_add_password
Create Date: 2026-01-02 10:45:46.845401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ead7175c3d0'
down_revision: Union[str, None] = '002_add_password'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_targets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('target', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('departments_division_code_unique'), 'departments', type_='unique')
    op.add_column('positions', sa.Column('target_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'positions', 'production_targets', ['target_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('plpc_unique'), 'production_log_problem_comments', type_='unique')
    op.add_column('sub_positions', sa.Column('target_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('sub_positions_position_id_code_key'), 'sub_positions', type_='unique')
    op.create_foreign_key(None, 'sub_positions', 'production_targets', ['target_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_positions', type_='foreignkey')
    op.create_unique_constraint(op.f('sub_positions_position_id_code_key'), 'sub_positions', ['position_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_column('sub_positions', 'target_id')
    op.create_unique_constraint(op.f('plpc_unique'), 'production_log_problem_comments', ['production_log_id', 'problem_comment_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_column('positions', 'target_id')
    op.create_unique_constraint(op.f('departments_division_code_unique'), 'departments', ['division_id', 'code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###

