"""add_name_to_positions

Revision ID: f9848fc5ad85
Revises: 2a2866fcadda
Create Date: 2026-01-02 14:22:53.634940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9848fc5ad85'
down_revision: Union[str, None] = '2a2866fcadda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('positions_target_id_fkey'), 'positions', type_='foreignkey')
    op.drop_column('positions', 'target_id')
    op.drop_constraint(op.f('sub_positions_target_id_fkey'), 'sub_positions', type_='foreignkey')
    op.drop_column('sub_positions', 'target_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_positions', sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sub_positions_target_id_fkey'), 'sub_positions', 'production_targets', ['target_id'], ['id'], ondelete='SET NULL')
    op.add_column('positions', sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('positions_target_id_fkey'), 'positions', 'production_targets', ['target_id'], ['id'], ondelete='SET NULL')
    op.drop_column('positions', 'name')
    # ### end Alembic commands ###

